SETUP

In [138]:
import pandas as pd
import sqlite3
import openpyxl

In [139]:
mer_df = pd.read_csv("csv_file/merchants.csv")
refund_df = pd.read_csv("csv_file/refunds.csv")
tran_info_df = pd.read_csv("csv_file/transaction_info.csv")
tran_df = pd.read_csv("csv_file/transactions.csv")

In [140]:
display(mer_df[:1])
display(refund_df[:1])
display(tran_info_df[:1])
display(tran_df[:1])

,merchant_id,leader_name,create_date,address,country,email,phone,industry
0,Richards-Little,Ms. Rachel Baker,2025-10-23,"7251 Patterson Station, New Jeremyshire, IL 72094",China,maciasandrew@simpson.info,206-857-7069x1009,Food & Beverage

,refund_id,tran_id,channel,amount,create_date,refund_date,reason,status
0,d0c37a23-9663-4410-89d3-62cfe87bb5e0,4a8c5a13-45de-451d-98ba-711f2cd9650a,DuitNow QR,45.74,2025-06-18 10:55:17,2025-06-25 10:55:17,Customer Dissatisfaction,completed

,tran_id,country,card_type,card_brands,region,channel_type
0,377a06dd-16de-4064-a464-da56c85039c8,Malaysia,NaN,NaN,Domestic,Buy Now Pay Later

,tran_id,merchant_id,channel,amount,currency,date,status
0,377a06dd-16de-4064-a464-da56c85039c8,"Townsend, Bishop and Mccoy",Shopee PayLater,46.95,MYR,2025-12-05 11:31:17,completed

In [141]:
# Create an in-memory SQLite database
conn = sqlite3.connect(":memory:")

# Load DataFrames into SQL tables
mer_df.to_sql("merchants", conn, index=False, if_exists='replace')
refund_df.to_sql("refunds", conn, index=False, if_exists='replace')
tran_info_df.to_sql("transaction_info", conn, index=False, if_exists='replace')
tran_df.to_sql("transactions", conn, index=False, if_exists='replace')

545668

GLOBAL FUNCTION

QUERY

In [142]:
sqlInput = f"""
SELECT t.merchant_id, COUNT(t.tran_id) as count
FROM transactions t
JOIN merchants m ON t.merchant_id = m.merchant_id
WHERE m.country = 'Singapore'
AND date BETWEEN '2025-12-31 00:00:00' AND '2025-12-31 23:59:59'
GROUP BY t.merchant_id
ORDER BY count DESC
"""

txn = pd.read_sql_query(sqlInput, conn)

display(txn[:10])

                    merchant_id  count
0    Townsend, Bishop and Mccoy      9
1       Roman, Willis and Rojas      5
2                    Owen Group      5
3                   Vega-Nelson      4
4  Romero, Morrison and Morales      4
5     Ramirez, Cruz and Patrick      4
6                Mejia and Sons      4
7     Smith, Cooper and Cabrera      2
8                 Dixon-Johnson      2
9                    Acosta PLC      2

In [143]:
merchant_id = txn['merchant_id'][0]
merchant_id

'Townsend, Bishop and Mccoy'

In [144]:
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker()
transactions = []

for _ in range(33):
    tran_id = fake.uuid4()
    
    years = [2022, 2023, 2024, 2025]
    year_weights = [1, 1.2, 1.8, 1.5]  

    year = random.choices(years, weights=year_weights)[0]

    start = datetime(2025, 12, 31, 11, 30, 00)
    end = datetime(2025, 12, 31, 11, 59, 59)

    trans_date = fake.date_time_between(start_date=start, end_date=end)

    amount_sgd = round(random.triangular(1, 30, 10), 2)

    transactions.append({
        'tran_id': tran_id,
        'merchant_id': merchant_id,
        'channel': 'DuitNow QR Offline',
        'amount': amount_sgd,
        'currency': 'SGD',
        'date': trans_date,
        'status': 'cancelled'
    })

cancelled_txn_df = pd.DataFrame(transactions)

display(cancelled_txn_df)

,tran_id,merchant_id,channel,amount,currency,date,status
0,418b2e81-ff57-4800-887f-fb8c8a9fdb72,"Townsend, Bishop and Mccoy",DuitNow QR Offline,10.08,SGD,2025-12-31 11:54:03,cancelled
1,91e63aa0-5efd-47c4-95d8-81808fe43aea,"Townsend, Bishop and Mccoy",DuitNow QR Offline,12.82,SGD,2025-12-31 11:56:38,cancelled
2,aabb5506-d546-46a0-82f1-8fe7390d4d51,"Townsend, Bishop and Mccoy",DuitNow QR Offline,5.40,SGD,2025-12-31 11:52:48,cancelled
3,95523b10-ee28-4b1b-a0b9-aedd8a6358da,"Townsend, Bishop and Mccoy",DuitNow QR Offline,17.08,SGD,2025-12-31 11:51:35,cancelled
4,2eccc13d-72a1-4fa5-a949-abdfd5a51bd7,"Townsend, Bishop and Mccoy",DuitNow QR Offline,17.92,SGD,2025-12-31 11:46:19,cancelled
5,c42144ff-728a-42f7-b4d2-07de5adf05b9,"Townsend, Bishop and Mccoy",DuitNow QR Offline,22.87,SGD,2025-12-31 11:49:58,cancelled
6,a4cf786a-76d7-4d06-8d59-ff6b6deec5ea,"Townsend, Bishop and Mccoy",DuitNow QR Offline,24.79,SGD,2025-12-31 11:30:04,cancelled
7,3fd53924-e5ce-4cb5-845b-9b32ef008fa3,"Townsend, Bishop and Mccoy",DuitNow QR Offline,8.77,SGD,2025-12-31 11:41:34,cancelled
8,c6e3c50e-7fb8-490a-b5f1-24e2459cf31b,"Townsend, Bishop and Mccoy",DuitNow QR Offline,20.78,SGD,2025-12-31 11:58:04,cancelled
9,ebfdaf93-8458-468d-984a-e1e6df232a8b,"Townsend, Bishop and Mccoy",DuitNow QR Offline,10.76,SGD,2025-12-31 11:33:55,cancelled
10,b7c4d889-f79b-46e0-b8a7-4bd600420602,"Townsend, Bishop and Mccoy",DuitNow QR Offline,26.52,SGD,2025-12-31 11:30:12,cancelled
11,e375cc3a-7b7c-4ccb-b90c-35a6c88126e8,"Townsend, Bishop and Mccoy",DuitNow QR Offline,12.00,SGD,2025-12-31 11:53:05,cancelled
12,6e0b5b52-7038-4c64-8d25-78cb385b1c09,"Townsend, Bishop and Mccoy",DuitNow QR Offline,12.15,SGD,2025-12-31 11:34:40,cancelled
13,16c409d4-9fdb-461c-8d82-010a7ac974fe,"Townsend, Bishop and Mccoy",DuitNow QR Offline,6.38,SGD,2025-12-31 11:34:13,cancelled
14,acdf439c-ecb9-425f-85da-b289163df344,"Townsend, Bishop and Mccoy",DuitNow QR Offline,27.86,SGD,2025-12-31 11:36:56,cancelled
15,a5fb774c-2682-4c25-81b9-a0cd30aff04b,"Townsend, Bishop and Mccoy",DuitNow QR Offline,6.80,SGD,2025-12-31 11:47:31,cancelled
16,b7d8bfc5-5f31-4879-8605-4f00ba8e18c8,"Townsend, Bishop and Mccoy",DuitNow QR Offline,18.41,SGD,2025-12-31 11:45:14,cancelled
17,33057879-d677-40c1-8d56-9772b95c0628,"Townsend, Bishop and Mccoy",DuitNow QR Offline,25.89,SGD,2025-12-31 11:30:11,cancelled
18,f81c67ee-b7c2-448f-8ac4-2b059c36c379,"Townsend, Bishop and Mccoy",DuitNow QR Offline,8.93,SGD,2025-12-31 11:39:34,cancelled
19,ea78dab5-751b-4c0d-9af3-3f9d9bf9e2ea,"Townsend, Bishop and Mccoy",DuitNow QR Offline,12.76,SGD,2025-12-31 11:39:56,cancelled
20,c68748b8-548b-465a-acfa-711c46fb1925,"Townsend, Bishop and Mccoy",DuitNow QR Offline,5.98,SGD,2025-12-31 11:38:05,cancelled
21,7015edc2-3869-4810-8115-4fe48c8c3e51,"Townsend, Bishop and Mccoy",DuitNow QR Offline,12.92,SGD,2025-12-31 11:37:42,cancelled
22,4bffef51-b755-47d5-9923-7c9dd3e4453d,"Townsend, Bishop and Mccoy",DuitNow QR Offline,19.61,SGD,2025-12-31 11:40:59,cancelled
23,5aa979e6-a344-42dc-8e7e-03a08d3180b3,"Townsend, Bishop and Mccoy",DuitNow QR Offline,24.07,SGD,2025-12-31 11:59:15,cancelled
24,eb9a0d06-dd8a-4ab1-827d-e43ba97189ae,"Townsend, Bishop and Mccoy",DuitNow QR Offline,23.77,SGD,2025-12-31 11:57:40,cancelled
25,bb7c206e-84fb-4902-be5f-2575085db6ca,"Townsend, Bishop and Mccoy",DuitNow QR Offline,5.89,SGD,2025-12-31 11:53:01,cancelled
26,9376ab1a-1cfc-44e2-bc50-487bef61eaf1,"Townsend, Bishop and Mccoy",DuitNow QR Offline,15.67,SGD,2025-12-31 11:37:58,cancelled
27,213f7cf6-cc62-407b-9074-cd377ec5fbcb,"Townsend, Bishop and Mccoy",DuitNow QR Offline,13.66,SGD,2025-12-31 11:56:32,cancelled
28,3e655c44-698f-412a-893b-18d7ea684e47,"Townsend, Bishop and Mccoy",DuitNow QR Offline,16.48,SGD,2025-12-31 11:45:23,cancelled
29,70b918ef-c93a-4c0e-b68b-dc0152ef5005,"Townsend, Bishop and Mccoy",DuitNow QR Offline,9.10,SGD,2025-12-31 11:40:28,cancelled
30,f964823e-2977-46fb-aa9d-63b87fde7cb3,"Townsend, Bishop and Mccoy",DuitNow QR Offline,20.27,SGD,2025-12-31 11:52:17,cancelled
31,2ec9dab0-ae44-4174-ad2e-cd7b7ad1996d,"Townsend, Bishop and Mccoy",DuitNow QR Offline,17.20,SGD,2025-12-31 11:35:39,cancelled
32,518b928e-0802-4772-a0b5-c8237711cb57,"Townsend, Bishop and Mccoy",DuitNow QR Offline,25.50,SGD,2025-12-31 11:45:42,cancelled

In [145]:
refunds = []

refund_reason_weights = {
    'Product Defect': 0.25,
    'Wrong Item Sent': 0.3,
    'Customer Dissatisfaction': 0.1,
    'Delayed Delivery': 0.15,
    'Fraudulent Transaction': 0.05,
    'Other': 0.15
}

for _, row in cancelled_txn_df.iterrows():

    tran_id = row['tran_id']
    tran_amount = row['amount']
    tran_date = row['date']
    channel = row['channel']

    channel_type = 'E-wallet Offline'
    status = 'completed'
    create_date = tran_date
    refund_date = tran_date
    refund_amount = tran_amount

    refunds.append({
        'refund_id': fake.uuid4(),
        'tran_id': tran_id,
        'channel': channel,
        'amount': refund_amount,
        'create_date': create_date,
        'refund_date': refund_date,
        'reason': random.choices(
            list(refund_reason_weights.keys()),
            weights=refund_reason_weights.values()
        )[0],
        'status': status
    })

cancelled_refunds_df = pd.DataFrame(refunds)

display(cancelled_refunds_df)

,refund_id,tran_id,channel,amount,create_date,refund_date,reason,status
0,447842a0-1efa-47ca-8b0a-aabca100b232,418b2e81-ff57-4800-887f-fb8c8a9fdb72,DuitNow QR Offline,10.08,2025-12-31 11:54:03,2025-12-31 11:54:03,Customer Dissatisfaction,completed
1,8da38d85-dd97-4cdc-98ce-49952e3eb715,91e63aa0-5efd-47c4-95d8-81808fe43aea,DuitNow QR Offline,12.82,2025-12-31 11:56:38,2025-12-31 11:56:38,Delayed Delivery,completed
2,33acc64e-3185-46d3-8972-f0663e621dbf,aabb5506-d546-46a0-82f1-8fe7390d4d51,DuitNow QR Offline,5.40,2025-12-31 11:52:48,2025-12-31 11:52:48,Product Defect,completed
3,74d4e4a0-b13b-49de-a56d-8cdaf708189f,95523b10-ee28-4b1b-a0b9-aedd8a6358da,DuitNow QR Offline,17.08,2025-12-31 11:51:35,2025-12-31 11:51:35,Delayed Delivery,completed
4,8856b62b-2677-42ee-8eab-02025bb8456b,2eccc13d-72a1-4fa5-a949-abdfd5a51bd7,DuitNow QR Offline,17.92,2025-12-31 11:46:19,2025-12-31 11:46:19,Product Defect,completed
5,03920a94-443b-4857-996a-ee5431040c72,c42144ff-728a-42f7-b4d2-07de5adf05b9,DuitNow QR Offline,22.87,2025-12-31 11:49:58,2025-12-31 11:49:58,Wrong Item Sent,completed
6,861ad533-c840-47fc-8a1f-4e5e73a5c108,a4cf786a-76d7-4d06-8d59-ff6b6deec5ea,DuitNow QR Offline,24.79,2025-12-31 11:30:04,2025-12-31 11:30:04,Wrong Item Sent,completed
7,82f77370-9e2d-400e-8eec-7831ad07e0fb,3fd53924-e5ce-4cb5-845b-9b32ef008fa3,DuitNow QR Offline,8.77,2025-12-31 11:41:34,2025-12-31 11:41:34,Delayed Delivery,completed
8,385edeed-7596-4281-98ed-bc4497364917,c6e3c50e-7fb8-490a-b5f1-24e2459cf31b,DuitNow QR Offline,20.78,2025-12-31 11:58:04,2025-12-31 11:58:04,Delayed Delivery,completed
9,f37d7332-77ce-4948-8441-45097dcfaa0f,ebfdaf93-8458-468d-984a-e1e6df232a8b,DuitNow QR Offline,10.76,2025-12-31 11:33:55,2025-12-31 11:33:55,Wrong Item Sent,completed
10,6e034cf7-0410-4e16-9f8e-b78e0a572a03,b7c4d889-f79b-46e0-b8a7-4bd600420602,DuitNow QR Offline,26.52,2025-12-31 11:30:12,2025-12-31 11:30:12,Delayed Delivery,completed
11,26a30530-b215-44f4-ad9b-730e06a0890c,e375cc3a-7b7c-4ccb-b90c-35a6c88126e8,DuitNow QR Offline,12.00,2025-12-31 11:53:05,2025-12-31 11:53:05,Delayed Delivery,completed
12,0bd6054d-24de-4679-ada2-4d33cd798a0b,6e0b5b52-7038-4c64-8d25-78cb385b1c09,DuitNow QR Offline,12.15,2025-12-31 11:34:40,2025-12-31 11:34:40,Fraudulent Transaction,completed
13,52f012ab-8800-43fb-b6a5-3aa15cc3f86d,16c409d4-9fdb-461c-8d82-010a7ac974fe,DuitNow QR Offline,6.38,2025-12-31 11:34:13,2025-12-31 11:34:13,Wrong Item Sent,completed
14,5ad8d7b2-06d2-403f-8b3f-db8c95febbc5,acdf439c-ecb9-425f-85da-b289163df344,DuitNow QR Offline,27.86,2025-12-31 11:36:56,2025-12-31 11:36:56,Customer Dissatisfaction,completed
15,c6db744f-dbf4-4259-ac75-67edbcc6e217,a5fb774c-2682-4c25-81b9-a0cd30aff04b,DuitNow QR Offline,6.80,2025-12-31 11:47:31,2025-12-31 11:47:31,Delayed Delivery,completed
16,59c445a5-3ddd-41d9-a647-c56a0886f4fa,b7d8bfc5-5f31-4879-8605-4f00ba8e18c8,DuitNow QR Offline,18.41,2025-12-31 11:45:14,2025-12-31 11:45:14,Wrong Item Sent,completed
17,f6d05c2b-c56c-42b4-9d25-b907f00fbbb7,33057879-d677-40c1-8d56-9772b95c0628,DuitNow QR Offline,25.89,2025-12-31 11:30:11,2025-12-31 11:30:11,Product Defect,completed
18,72f875bd-29f2-4882-ab4e-d5a036320c5b,f81c67ee-b7c2-448f-8ac4-2b059c36c379,DuitNow QR Offline,8.93,2025-12-31 11:39:34,2025-12-31 11:39:34,Other,completed
19,725e8dab-a4b6-48f6-87cd-dfa89c13db3f,ea78dab5-751b-4c0d-9af3-3f9d9bf9e2ea,DuitNow QR Offline,12.76,2025-12-31 11:39:56,2025-12-31 11:39:56,Wrong Item Sent,completed
20,ba2567a3-2b85-4d4c-ad3e-72e629f553ab,c68748b8-548b-465a-acfa-711c46fb1925,DuitNow QR Offline,5.98,2025-12-31 11:38:05,2025-12-31 11:38:05,Product Defect,completed
21,5d0af55a-8760-404d-9bc4-58dd2474cccd,7015edc2-3869-4810-8115-4fe48c8c3e51,DuitNow QR Offline,12.92,2025-12-31 11:37:42,2025-12-31 11:37:42,Delayed Delivery,completed
22,97e9c1aa-2e0a-44eb-9d3c-14068c8d4e9b,4bffef51-b755-47d5-9923-7c9dd3e4453d,DuitNow QR Offline,19.61,2025-12-31 11:40:59,2025-12-31 11:40:59,Wrong Item Sent,completed
23,e66607cc-40f8-44eb-8bea-9da29c21a77a,5aa979e6-a344-42dc-8e7e-03a08d3180b3,DuitNow QR Offline,24.07,2025-12-31 11:59:15,2025-12-31 11:59:15,Fraudulent Transaction,completed
24,b2baac93-1e2c-474c-a760-4336141d3e6e,eb9a0d06-dd8a-4ab1-827d-e43ba97189ae,DuitNow QR Offline,23.77,2025-12-31 11:57:40,2025-12-31 11:57:40,Product Defect,completed
25,2d79292f-62b7-4eab-8fd1-0eba261e957a,bb7c206e-84fb-4902-be5f-2575085db6ca,DuitNow QR Offline,5.89,2025-12-31 11:53:01,2025-12-31 11:53:01,Wrong Item Sent,completed
26,f9485ba7-5ac0-486f-ba0e-23f83ca0a050,9376ab1a-1cfc-44e2-bc50-487bef61eaf1,DuitNow QR Offline,15.67,2025-12-31 11:37:58,2025-12-31 11:37:58,Fraudulent Transaction,completed
27,28fb70a8-ed3d-4d0f-a4bd-215b94c4e700,213f7cf6-cc62-407b-9074-cd377ec5fbcb,DuitNow QR Offline,13.66,2025-12-31 11:56:32,2025-12-31 11:56:32,Delayed Delivery,completed
28,425b82b1-a0ae-4fe0-892f-8703d7d4be28,3e655c44-698f-412a-893b-18d7ea684e47,DuitNow QR Offline,16.48,2025-12-31 11:45:23,2025-12-31 11:45:23,Delayed Delivery,completed
29,9f42e611-83d3-4fe4-bf84-4c602d69c989,70b918ef-c93a-4c0e-b68b-dc0152ef5005,DuitNow QR Offline,9.10,2025-12-31 11:40:28,2025-12-31 11:40:28,Fraudulent Transaction,completed
30,81b3aa0c-fa14-43b0-b8c2-2003451e525b,f964823e-2977-46fb-aa9d-63b87fde7cb3,DuitNow QR Offline,20.27,2025-12-31 11:52:17,2025-12-31 11:52:17,Customer Dissatisfaction,completed
31,6a0f1e64-f806-41c6-ae5b-7915c897931a,2ec9dab0-ae44-4174-ad2e-cd7b7ad1996d,DuitNow QR Offline,17.20,2025-12-31 11:35:39,2025-12-31 11:35:39,Other,completed
32,5a1d0e49-b6da-4430-a830-e287ab45f065,518b928e-0802-4772-a0b5-c8237711cb57,DuitNow QR Offline,25.50,2025-12-31 11:45:42,2025-12-31 11:45:42,Product Defect,completed

In [146]:
transaction_info = []

for _, row in cancelled_txn_df.iterrows():
    region = "Foreign"
    channel_type = 'E-wallet Offline'

    card_brands, card_type = None, None
    
    country = 'Singapore'

    transaction_info.append({
        'tran_id': row['tran_id'],
        'country': country,
        'card_type': card_type,
        'card_brands': card_brands,
        'region': region,
        'channel_type': channel_type
    })

cancelled_txn_info = pd.DataFrame(transaction_info)
display(cancelled_txn_info)

,tran_id,country,card_type,card_brands,region,channel_type
0,418b2e81-ff57-4800-887f-fb8c8a9fdb72,Singapore,None,None,Foreign,E-wallet Offline
1,91e63aa0-5efd-47c4-95d8-81808fe43aea,Singapore,None,None,Foreign,E-wallet Offline
2,aabb5506-d546-46a0-82f1-8fe7390d4d51,Singapore,None,None,Foreign,E-wallet Offline
3,95523b10-ee28-4b1b-a0b9-aedd8a6358da,Singapore,None,None,Foreign,E-wallet Offline
4,2eccc13d-72a1-4fa5-a949-abdfd5a51bd7,Singapore,None,None,Foreign,E-wallet Offline
5,c42144ff-728a-42f7-b4d2-07de5adf05b9,Singapore,None,None,Foreign,E-wallet Offline
6,a4cf786a-76d7-4d06-8d59-ff6b6deec5ea,Singapore,None,None,Foreign,E-wallet Offline
7,3fd53924-e5ce-4cb5-845b-9b32ef008fa3,Singapore,None,None,Foreign,E-wallet Offline
8,c6e3c50e-7fb8-490a-b5f1-24e2459cf31b,Singapore,None,None,Foreign,E-wallet Offline
9,ebfdaf93-8458-468d-984a-e1e6df232a8b,Singapore,None,None,Foreign,E-wallet Offline
10,b7c4d889-f79b-46e0-b8a7-4bd600420602,Singapore,None,None,Foreign,E-wallet Offline
11,e375cc3a-7b7c-4ccb-b90c-35a6c88126e8,Singapore,None,None,Foreign,E-wallet Offline
12,6e0b5b52-7038-4c64-8d25-78cb385b1c09,Singapore,None,None,Foreign,E-wallet Offline
13,16c409d4-9fdb-461c-8d82-010a7ac974fe,Singapore,None,None,Foreign,E-wallet Offline
14,acdf439c-ecb9-425f-85da-b289163df344,Singapore,None,None,Foreign,E-wallet Offline
15,a5fb774c-2682-4c25-81b9-a0cd30aff04b,Singapore,None,None,Foreign,E-wallet Offline
16,b7d8bfc5-5f31-4879-8605-4f00ba8e18c8,Singapore,None,None,Foreign,E-wallet Offline
17,33057879-d677-40c1-8d56-9772b95c0628,Singapore,None,None,Foreign,E-wallet Offline
18,f81c67ee-b7c2-448f-8ac4-2b059c36c379,Singapore,None,None,Foreign,E-wallet Offline
19,ea78dab5-751b-4c0d-9af3-3f9d9bf9e2ea,Singapore,None,None,Foreign,E-wallet Offline
20,c68748b8-548b-465a-acfa-711c46fb1925,Singapore,None,None,Foreign,E-wallet Offline
21,7015edc2-3869-4810-8115-4fe48c8c3e51,Singapore,None,None,Foreign,E-wallet Offline
22,4bffef51-b755-47d5-9923-7c9dd3e4453d,Singapore,None,None,Foreign,E-wallet Offline
23,5aa979e6-a344-42dc-8e7e-03a08d3180b3,Singapore,None,None,Foreign,E-wallet Offline
24,eb9a0d06-dd8a-4ab1-827d-e43ba97189ae,Singapore,None,None,Foreign,E-wallet Offline
25,bb7c206e-84fb-4902-be5f-2575085db6ca,Singapore,None,None,Foreign,E-wallet Offline
26,9376ab1a-1cfc-44e2-bc50-487bef61eaf1,Singapore,None,None,Foreign,E-wallet Offline
27,213f7cf6-cc62-407b-9074-cd377ec5fbcb,Singapore,None,None,Foreign,E-wallet Offline
28,3e655c44-698f-412a-893b-18d7ea684e47,Singapore,None,None,Foreign,E-wallet Offline
29,70b918ef-c93a-4c0e-b68b-dc0152ef5005,Singapore,None,None,Foreign,E-wallet Offline
30,f964823e-2977-46fb-aa9d-63b87fde7cb3,Singapore,None,None,Foreign,E-wallet Offline
31,2ec9dab0-ae44-4174-ad2e-cd7b7ad1996d,Singapore,None,None,Foreign,E-wallet Offline
32,518b928e-0802-4772-a0b5-c8237711cb57,Singapore,None,None,Foreign,E-wallet Offline

In [147]:
updated_txns = pd.concat([tran_df, cancelled_txn_df])
updated_refunds = pd.concat([refund_df, cancelled_refunds_df])
updated_txn_info = pd.concat([tran_info_df, cancelled_txn_info])

output_folder = 'csv_file'

updated_txns.to_csv(f'{output_folder}/transactions.csv', index=False)
updated_refunds.to_csv(f'{output_folder}/refunds.csv', index=False)
updated_txn_info.to_csv(f'{output_folder}/transaction_info.csv', index=False)

In [148]:
mer_df = pd.read_csv("csv_file/merchants.csv")
refund_df = pd.read_csv("csv_file/refunds.csv")
tran_info_df = pd.read_csv("csv_file/transaction_info.csv")
tran_df = pd.read_csv("csv_file/transactions.csv")

conn = sqlite3.connect("payments.db")

mer_df.to_sql("merchants", conn, index=False, if_exists='replace')
refund_df.to_sql("refunds", conn, index=False, if_exists='replace')
tran_info_df.to_sql("transaction_info", conn, index=False, if_exists='replace')
tran_df.to_sql("transactions", conn, index=False, if_exists='replace')

545701

Checking

In [149]:
sqlInput = f"""
SELECT t.date, t.merchant_id, t.tran_id, t.status, t.currency,
    r.refund_id, r.status, r.create_date, r.refund_date
FROM transactions t
LEFT JOIN refunds r ON t.tran_id = r.tran_id
WHERE t.date BETWEEN '2025-12-31 00:00:00' AND '2025-12-31 23:59:59'
AND t.merchant_id = '{merchant_id}'
"""

txncheck = pd.read_sql_query(sqlInput, conn)

display(txncheck)

,date,merchant_id,tran_id,status,currency,refund_id,status,create_date,refund_date
0,2025-12-31 23:43:17,"Townsend, Bishop and Mccoy",2494b5c1-c6c6-42b2-b731-60bfc908be89,recorded,MYR,36f0a19a-2c3e-4adf-9bb4-26f71815c640,pending,2025-12-31 23:43:17,None
1,2025-12-31 09:17:08,"Townsend, Bishop and Mccoy",c1edd2f0-3213-41db-b772-48c0c2c92654,pending,THB,None,None,None,None
2,2025-12-31 06:47:16,"Townsend, Bishop and Mccoy",2e680961-1e70-4bfe-b042-619110c03fbe,pending,MYR,None,None,None,None
3,2025-12-31 12:14:52,"Townsend, Bishop and Mccoy",ad526eba-d789-4fdf-b73a-366e2f84ec3a,recorded,MYR,None,None,None,None
4,2025-12-31 08:13:51,"Townsend, Bishop and Mccoy",40611d2f-1c93-4c63-b00b-d032ecaeb4bb,pending,MYR,None,None,None,None
5,2025-12-31 03:56:49,"Townsend, Bishop and Mccoy",960b249d-68bf-474f-a751-fb8675352128,pending,SGD,None,None,None,None
6,2025-12-31 22:26:51,"Townsend, Bishop and Mccoy",3c7c3cd6-c442-4602-81f1-79e84ece1111,recorded,CNY,None,None,None,None
7,2025-12-31 17:37:52,"Townsend, Bishop and Mccoy",d0fad0e5-b62c-4632-ad9e-a0171c0325aa,pending,MYR,None,None,None,None
8,2025-12-31 17:16:00,"Townsend, Bishop and Mccoy",2cb78c75-deb8-4835-a44a-7a8dd1c4e925,pending,MYR,None,None,None,None
9,2025-12-31 11:54:03,"Townsend, Bishop and Mccoy",418b2e81-ff57-4800-887f-fb8c8a9fdb72,cancelled,SGD,447842a0-1efa-47ca-8b0a-aabca100b232,completed,2025-12-31 11:54:03,2025-12-31 11:54:03
10,2025-12-31 11:56:38,"Townsend, Bishop and Mccoy",91e63aa0-5efd-47c4-95d8-81808fe43aea,cancelled,SGD,8da38d85-dd97-4cdc-98ce-49952e3eb715,completed,2025-12-31 11:56:38,2025-12-31 11:56:38
11,2025-12-31 11:52:48,"Townsend, Bishop and Mccoy",aabb5506-d546-46a0-82f1-8fe7390d4d51,cancelled,SGD,33acc64e-3185-46d3-8972-f0663e621dbf,completed,2025-12-31 11:52:48,2025-12-31 11:52:48
12,2025-12-31 11:51:35,"Townsend, Bishop and Mccoy",95523b10-ee28-4b1b-a0b9-aedd8a6358da,cancelled,SGD,74d4e4a0-b13b-49de-a56d-8cdaf708189f,completed,2025-12-31 11:51:35,2025-12-31 11:51:35
13,2025-12-31 11:46:19,"Townsend, Bishop and Mccoy",2eccc13d-72a1-4fa5-a949-abdfd5a51bd7,cancelled,SGD,8856b62b-2677-42ee-8eab-02025bb8456b,completed,2025-12-31 11:46:19,2025-12-31 11:46:19
14,2025-12-31 11:49:58,"Townsend, Bishop and Mccoy",c42144ff-728a-42f7-b4d2-07de5adf05b9,cancelled,SGD,03920a94-443b-4857-996a-ee5431040c72,completed,2025-12-31 11:49:58,2025-12-31 11:49:58
15,2025-12-31 11:30:04,"Townsend, Bishop and Mccoy",a4cf786a-76d7-4d06-8d59-ff6b6deec5ea,cancelled,SGD,861ad533-c840-47fc-8a1f-4e5e73a5c108,completed,2025-12-31 11:30:04,2025-12-31 11:30:04
16,2025-12-31 11:41:34,"Townsend, Bishop and Mccoy",3fd53924-e5ce-4cb5-845b-9b32ef008fa3,cancelled,SGD,82f77370-9e2d-400e-8eec-7831ad07e0fb,completed,2025-12-31 11:41:34,2025-12-31 11:41:34
17,2025-12-31 11:58:04,"Townsend, Bishop and Mccoy",c6e3c50e-7fb8-490a-b5f1-24e2459cf31b,cancelled,SGD,385edeed-7596-4281-98ed-bc4497364917,completed,2025-12-31 11:58:04,2025-12-31 11:58:04
18,2025-12-31 11:33:55,"Townsend, Bishop and Mccoy",ebfdaf93-8458-468d-984a-e1e6df232a8b,cancelled,SGD,f37d7332-77ce-4948-8441-45097dcfaa0f,completed,2025-12-31 11:33:55,2025-12-31 11:33:55
19,2025-12-31 11:30:12,"Townsend, Bishop and Mccoy",b7c4d889-f79b-46e0-b8a7-4bd600420602,cancelled,SGD,6e034cf7-0410-4e16-9f8e-b78e0a572a03,completed,2025-12-31 11:30:12,2025-12-31 11:30:12
20,2025-12-31 11:53:05,"Townsend, Bishop and Mccoy",e375cc3a-7b7c-4ccb-b90c-35a6c88126e8,cancelled,SGD,26a30530-b215-44f4-ad9b-730e06a0890c,completed,2025-12-31 11:53:05,2025-12-31 11:53:05
21,2025-12-31 11:34:40,"Townsend, Bishop and Mccoy",6e0b5b52-7038-4c64-8d25-78cb385b1c09,cancelled,SGD,0bd6054d-24de-4679-ada2-4d33cd798a0b,completed,2025-12-31 11:34:40,2025-12-31 11:34:40
22,2025-12-31 11:34:13,"Townsend, Bishop and Mccoy",16c409d4-9fdb-461c-8d82-010a7ac974fe,cancelled,SGD,52f012ab-8800-43fb-b6a5-3aa15cc3f86d,completed,2025-12-31 11:34:13,2025-12-31 11:34:13
23,2025-12-31 11:36:56,"Townsend, Bishop and Mccoy",acdf439c-ecb9-425f-85da-b289163df344,cancelled,SGD,5ad8d7b2-06d2-403f-8b3f-db8c95febbc5,completed,2025-12-31 11:36:56,2025-12-31 11:36:56
24,2025-12-31 11:47:31,"Townsend, Bishop and Mccoy",a5fb774c-2682-4c25-81b9-a0cd30aff04b,cancelled,SGD,c6db744f-dbf4-4259-ac75-67edbcc6e217,completed,2025-12-31 11:47:31,2025-12-31 11:47:31
25,2025-12-31 11:45:14,"Townsend, Bishop and Mccoy",b7d8bfc5-5f31-4879-8605-4f00ba8e18c8,cancelled,SGD,59c445a5-3ddd-41d9-a647-c56a0886f4fa,completed,2025-12-31 11:45:14,2025-12-31 11:45:14
26,2025-12-31 11:30:11,"Townsend, Bishop and Mccoy",33057879-d677-40c1-8d56-9772b95c0628,cancelled,SGD,f6d05c2b-c56c-42b4-9d25-b907f00fbbb7,completed,2025-12-31 11:30:11,2025-12-31 11:30:11
27,2025-12-31 11:39:34,"Townsend, Bishop and Mccoy",f81c67ee-b7c2-448f-8ac4-2b059c36c379,cancelled,SGD,72f875bd-29f2-4882-ab4e-d5a036320c5b,completed,2025-12-31 11:39:34,2025-12-31 11:39:34
28,2025-12-31 11:39:56,"Townsend, Bishop and Mccoy",ea78dab5-751b-4c0d-9af3-3f9d9bf9e2ea,cancelled,SGD,725e8dab-a4b6-48f6-87cd-dfa89c13db3f,completed,2025-12-31 11:39:56,2025-12-31 11:39:56
29,2025-12-31 11:38:05,"Townsend, Bishop and Mccoy",c68748b8-548b-465a-acfa-711c46fb1925,cancelled,SGD,ba2567a3-2b85-4d4c-ad3e-72e629f553ab,completed,2025-12-31 11:38:05,2025-12-31 11:38:05
30,2025-12-31 11:37:42,"Townsend, Bishop and Mccoy",7015edc2-3869-4810-8115-4fe48c8c3e51,cancelled,SGD,5d0af55a-8760-404d-9bc4-58dd2474cccd,completed,2025-12-31 11:37:42,2025-12-31 11:37:42
31,2025-12-31 11:40:59,"Townsend, Bishop and Mccoy",4bffef51-b755-47d5-9923-7c9dd3e4453d,cancelled,SGD,97e9c1aa-2e0a-44eb-9d3c-14068c8d4e9b,completed,2025-12-31 11:40:59,2025-12-31 11:40:59
32,2025-12-31 11:59:15,"Townsend, Bishop and Mccoy",5aa979e6-a344-42dc-8e7e-03a08d3180b3,cancelled,SGD,e66607cc-40f8-44eb-8bea-9da29c21a77a,completed,2025-12-31 11:59:15,2025-12-31 11:59:15
33,2025-12-31 11:57:40,"Townsend, Bishop and Mccoy",eb9a0d06-dd8a-4ab1-827d-e43ba97189ae,cancelled,SGD,b2baac93-1e2c-474c-a760-4336141d3e6e,completed,2025-12-31 11:57:40,2025-12-31 11:57:40
34,2025-12-31 11:53:01,"Townsend, Bishop and Mccoy",bb7c206e-84fb-4902-be5f-2575085db6ca,cancelled,SGD,2d79292f-62b7-4eab-8fd1-0eba261e957a,completed,2025-12-31 11:53:01,2025-12-31 11:53:01
35,2025-12-31 11:37:58,"Townsend, Bishop and Mccoy",9376ab1a-1cfc-44e2-bc50-487bef61eaf1,cancelled,SGD,f9485ba7-5ac0-486f-ba0e-23f83ca0a050,completed,2025-12-31 11:37:58,2025-12-31 11:37:58
36,2025-12-31 11:56:32,"Townsend, Bishop and Mccoy",213f7cf6-cc62-407b-9074-cd377ec5fbcb,cancelled,SGD,28fb70a8-ed3d-4d0f-a4bd-215b94c4e700,completed,2025-12-31 11:56:32,2025-12-31 11:56:32
37,2025-12-31 11:45:23,"Townsend, Bishop and Mccoy",3e655c44-698f-412a-893b-18d7ea684e47,cancelled,SGD,425b82b1-a0ae-4fe0-892f-8703d7d4be28,completed,2025-12-31 11:45:23,2025-12-31 11:45:23
38,2025-12-31 11:40:28,"Townsend, Bishop and Mccoy",70b918ef-c93a-4c0e-b68b-dc0152ef5005,cancelled,SGD,9f42e611-83d3-4fe4-bf84-4c602d69c989,completed,2025-12-31 11:40:28,2025-12-31 11:40:28
39,2025-12-31 11:52:17,"Townsend, Bishop and Mccoy",f964823e-2977-46fb-aa9d-63b87fde7cb3,cancelled,SGD,81b3aa0c-fa14-43b0-b8c2-2003451e525b,completed,2025-12-31 11:52:17,2025-12-31 11:52:17
40,2025-12-31 11:35:39,"Townsend, Bishop and Mccoy",2ec9dab0-ae44-4174-ad2e-cd7b7ad1996d,cancelled,SGD,6a0f1e64-f806-41c6-ae5b-7915c897931a,completed,2025-12-31 11:35:39,2025-12-31 11:35:39
41,2025-12-31 11:45:42,"Townsend, Bishop and Mccoy",518b928e-0802-4772-a0b5-c8237711cb57,cancelled,SGD,5a1d0e49-b6da-4430-a830-e287ab45f065,completed,2025-12-31 11:45:42,2025-12-31 11:45:42